import PDFDocument from 'pdfkit';

interface CandidateReport {
  full_name: string;
  email: string;
  phone?: string;
  status: string;
  submitted_at: string;
  ai_analysis?: {
    overall_score: number;
    category: string;
    scores: Record<string, number>;
    strengths: string[];
    weaknesses: string[];
    summary: string;
    recommendations: string[];
  };
  vacancy_title?: string;
}

export function generateCandidateReport(candidate: CandidateReport): PDFKit.PDFDocument {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });

  const orange = '#E8721C';
  const dark = '#1a1a1a';
  const gray = '#666666';
  const lightGray = '#999999';

  // Header with SOLUTION branding
  doc.rect(0, 0, 595, 80).fill(dark);
  doc.fontSize(24).fillColor('#ffffff').text('SOLUTION', 50, 25, { continued: true });
  doc.fontSize(10).fillColor(orange).text('  AI RECRUITER', { continued: false });
  doc.fontSize(8).fillColor(lightGray).text('Otchyot po kandidatu', 50, 52);
  doc.fontSize(8).text(new Date().toLocaleDateString('ru-RU', { day: '2-digit', month: 'long', year: 'numeric' }), 400, 52, { align: 'right' });

  doc.moveDown(3);

  // Candidate info
  doc.fontSize(20).fillColor(dark).text(candidate.full_name, 50);
  doc.moveDown(0.3);
  if (candidate.vacancy_title) {
    doc.fontSize(10).fillColor(gray).text(`Vacancy: ${candidate.vacancy_title}`);
  }
  doc.fontSize(9).fillColor(lightGray);
  if (candidate.email) doc.text(`Email: ${candidate.email}`);
  if (candidate.phone) doc.text(`Phone: ${candidate.phone}`);
  doc.text(`Submitted: ${new Date(candidate.submitted_at).toLocaleDateString('ru-RU')}`);

  doc.moveDown(1.5);

  if (candidate.ai_analysis) {
    const a = candidate.ai_analysis;

    // Overall score
    doc.rect(50, doc.y, 495, 60).fillAndStroke('#f5f5f5', '#e0e0e0');
    const scoreY = doc.y + 10;
    doc.fontSize(14).fillColor(dark).text('Overall score:', 70, scoreY);
    doc.fontSize(28).fillColor(orange).text(`${a.overall_score}/100`, 200, scoreY - 5);
    const catLabel = a.category === 'excellent' ? 'Excellent' : a.category === 'good' ? 'Good' : a.category === 'average' ? 'Average' : 'Below average';
    const catColor = a.category === 'excellent' ? '#10b981' : a.category === 'good' ? '#3b82f6' : a.category === 'average' ? '#f59e0b' : '#ef4444';
    doc.fontSize(12).fillColor(catColor).text(catLabel, 320, scoreY + 5);

    doc.y = scoreY + 55;
    doc.moveDown(1);

    // Scores breakdown
    doc.fontSize(13).fillColor(dark).text('Score breakdown', 50);
    doc.moveDown(0.5);

    const scoreLabels: Record<string, string> = {
      hard_skills: 'Hard Skills',
      experience: 'Experience',
      education: 'Education',
      soft_skills: 'Soft Skills',
      languages: 'Languages',
      culture_fit: 'Culture Fit',
    };

    Object.entries(a.scores || {}).forEach(([key, value]) => {
      const label = scoreLabels[key] || key;
      const barWidth = 300;
      const fillWidth = (Number(value) / 100) * barWidth;
      const y = doc.y;

      doc.fontSize(9).fillColor(gray).text(label, 50, y, { width: 150 });
      doc.rect(200, y + 2, barWidth, 10).fill('#e0e0e0');
      doc.rect(200, y + 2, fillWidth, 10).fill(orange);
      doc.fontSize(9).fillColor(dark).text(`${value}%`, 510, y);
      doc.y = y + 20;
    });

    doc.moveDown(1);

    // Summary
    doc.fontSize(13).fillColor(dark).text('AI Summary', 50);
    doc.moveDown(0.3);
    doc.fontSize(9).fillColor(gray).text(a.summary || 'No data', 50, doc.y, { width: 495 });

    doc.moveDown(1);

    // Strengths
    if (a.strengths?.length) {
      doc.fontSize(12).fillColor('#10b981').text('Strengths', 50);
      doc.moveDown(0.3);
      a.strengths.forEach(s => {
        doc.fontSize(9).fillColor(gray).text(`  - ${s}`, 60);
      });
      doc.moveDown(0.5);
    }

    // Weaknesses
    if (a.weaknesses?.length) {
      doc.fontSize(12).fillColor('#ef4444').text('Areas for improvement', 50);
      doc.moveDown(0.3);
      a.weaknesses.forEach(w => {
        doc.fontSize(9).fillColor(gray).text(`  - ${w}`, 60);
      });
      doc.moveDown(0.5);
    }

    // Recommendations
    if (a.recommendations?.length) {
      doc.fontSize(12).fillColor(orange).text('Recommendations', 50);
      doc.moveDown(0.3);
      a.recommendations.forEach((r, i) => {
        doc.fontSize(9).fillColor(gray).text(`  ${i + 1}. ${r}`, 60);
      });
    }
  } else {
    doc.fontSize(12).fillColor(gray).text('AI analysis has not been performed yet', 50);
  }

  // Footer
  doc.fontSize(7).fillColor(lightGray).text(
    'Generated by SOLUTION AI Recruiter - Confidential',
    50, 770, { align: 'center', width: 495 }
  );

  return doc;
}
