export const mockVacancies = [
  {
    id: '1',
    title: 'Senior Backend Developer',
    status: 'active',
    location: 'Tashkent',
    remote: false,
    created_at: '2026-02-10T10:00:00Z',
    hard_skills: ['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'Redis'],
    candidates_count: 12,
    analyzed_count: 9,
    avg_score: 74,
    google_form_url: '#',
    salary_range: { min: 3000, max: 5000, currency: 'USD' },
  },
  {
    id: '2',
    title: 'Frontend Developer (React)',
    status: 'active',
    location: 'Tashkent',
    remote: true,
    created_at: '2026-02-18T09:00:00Z',
    hard_skills: ['React', 'TypeScript', 'Tailwind CSS', 'Next.js'],
    candidates_count: 8,
    analyzed_count: 6,
    avg_score: 68,
    google_form_url: '#',
    salary_range: { min: 2000, max: 3500, currency: 'USD' },
  },
  {
    id: '3',
    title: 'DevOps Engineer',
    status: 'paused',
    location: 'Remote',
    remote: true,
    created_at: '2026-01-25T11:00:00Z',
    hard_skills: ['Kubernetes', 'AWS', 'Terraform', 'CI/CD', 'Linux'],
    candidates_count: 5,
    analyzed_count: 5,
    avg_score: 61,
    google_form_url: '#',
    salary_range: { min: 3500, max: 6000, currency: 'USD' },
  },
];

export const mockCandidates = [
  {
    id: '1', vacancy_id: '1', full_name: 'Алексей Иванов', email: 'alexey@example.com',
    phone: '+998 90 123 45 67', submitted_at: '2026-02-15T09:30:00Z', status: 'analyzed',
    linkedin_url: 'https://linkedin.com/in/alexeyivanov',
    overall_score: 92, category: 'excellent',
    scores: { hard_skills: 95, experience: 90, education: 88, soft_skills: 85, languages: 95, culture_fit: 90 },
    strengths: ['7 лет опыта Python и FastAPI', 'Свободный английский (C1)', 'Опыт в банковском секторе (Ipoteka Bank)'],
    weaknesses: ['Ограниченный опыт с Kubernetes', 'Нет опыта с GraphQL', 'Мало информации о менторинге'],
    summary: 'Исключительный кандидат с сильным техническим бэкграундом и релевантным опытом в банковском секторе. Технические навыки превышают требования вакансии. Настоятельно рекомендуется к немедленному собеседованию.',
    recommendations: ['Обсудить архитектурные решения для высоконагруженных систем', 'Уточнить знание регуляторных требований ЦБ РУз', 'Проверить soft skills и лидерский потенциал'],
    green_flags: ['Banking experience', 'Multi-lingual', 'Senior Python'],
    red_flags: [],
    growth_potential: 'high',
    form_responses: { 'Образование': 'ТУИТ, Прикладная математика, 2017', 'Опыт работы': '7 лет backend разработки. Ipoteka Bank (2021-2026) — Lead Backend Developer. Разработал систему онлайн-кредитования. Olx Uzbekistan (2018-2021) — Senior Python Developer.', 'Технические навыки': ['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'Redis'], 'Ожидаемая зарплата (USD в месяц)': '4500' },
  },
  {
    id: '2', vacancy_id: '1', full_name: 'Дилшод Рашидов', email: 'dilshod@example.com',
    phone: '+998 91 234 56 78', submitted_at: '2026-02-16T14:00:00Z', status: 'analyzed',
    overall_score: 81, category: 'good',
    scores: { hard_skills: 85, experience: 78, education: 80, soft_skills: 75, languages: 82, culture_fit: 78 },
    strengths: ['Хорошие технические навыки Python/Django', 'Опыт работы в fintech', 'Трёхъязычный специалист'],
    weaknesses: ['FastAPI не в опыте (только Django)', 'Опыт 4 года вместо требуемых 5', 'Мало опыта с Redis'],
    summary: 'Сильный кандидат с хорошими навыками. Основной пробел — отсутствие опыта с FastAPI и Redis. При должном onboarding может быстро восполнить пробелы.',
    recommendations: ['Оценить способность быстро освоить FastAPI', 'Обсудить опыт работы с платёжными системами', 'Проверить знание SQL оптимизации'],
    green_flags: ['Fintech experience', 'Strong Python'],
    red_flags: [],
    growth_potential: 'high',
    form_responses: { 'Образование': 'НУУз, Информационные технологии, 2020', 'Опыт работы': '4 года. Payme (2022-2026) — Backend Developer. Click (2020-2022) — Junior Developer.', 'Технические навыки': ['Python', 'Django', 'PostgreSQL', 'Docker'], 'Ожидаемая зарплата (USD в месяц)': '3500' },
  },
  {
    id: '3', vacancy_id: '1', full_name: 'Камола Юсупова', email: 'kamola@example.com',
    phone: '+998 93 345 67 89', submitted_at: '2026-02-17T11:00:00Z', status: 'invited',
    overall_score: 88, category: 'good',
    scores: { hard_skills: 90, experience: 85, education: 92, soft_skills: 88, languages: 90, culture_fit: 85 },
    strengths: ['Магистр CS (МГТУ им. Баумана)', 'Опыт в международных проектах', 'Отличные коммуникативные навыки'],
    weaknesses: ['Меньше опыта в банковском секторе', 'Нет Docker в продакшн опыте'],
    summary: 'Высококвалифицированный специалист с международным опытом и отличным образованием. Рекомендуется к собеседованию.',
    recommendations: ['Обсудить планы по переезду / удалённой работе', 'Уточнить опыт с highload системами'],
    green_flags: ['International experience', 'Master degree', 'Strong communicator'],
    red_flags: [],
    growth_potential: 'high',
    form_responses: { 'Образование': 'МГТУ им. Баумана, Computer Science, Магистр, 2019', 'Опыт работы': '6 лет. Yandex (2021-2026) — Senior Backend. Mail.ru (2019-2021) — Backend Developer.', 'Технические навыки': ['Python', 'FastAPI', 'PostgreSQL', 'Redis', 'Kubernetes'], 'Ожидаемая зарплата (USD в месяц)': '5000' },
  },
  {
    id: '4', vacancy_id: '1', full_name: 'Бобур Каримов', email: 'bobur@example.com',
    phone: '+998 94 456 78 90', submitted_at: '2026-02-18T10:00:00Z', status: 'analyzed',
    overall_score: 58, category: 'below',
    scores: { hard_skills: 55, experience: 50, education: 65, soft_skills: 60, languages: 65, culture_fit: 55 },
    strengths: ['Хорошее базовое образование', 'Знание Python основ', 'Мотивированный кандидат'],
    weaknesses: ['Только 2 года опыта (требуется 5)', 'Нет опыта с Docker и Redis', 'Нет опыта в коммерческих проектах'],
    summary: 'Кандидат с потенциалом, но значительно уступает требованиям вакансии по опыту. Рекомендуется рассмотреть на позицию Junior/Middle.',
    recommendations: ['Оценить на Junior позицию', 'Проверить базовые знания Python'],
    green_flags: ['Motivated', 'Good education'],
    red_flags: ['Insufficient experience'],
    growth_potential: 'medium',
    form_responses: { 'Образование': 'ТУИТ, 2023', 'Опыт работы': '2 года. Фриланс проекты, стажировка.', 'Технические навыки': ['Python', 'PostgreSQL'], 'Ожидаемая зарплата (USD в месяц)': '1500' },
  },
  {
    id: '5', vacancy_id: '1', full_name: 'Санжар Мирзаев', email: 'sanzhar@example.com',
    phone: '+998 95 567 89 01', submitted_at: '2026-02-19T09:00:00Z', status: 'new',
    overall_score: 0, category: 'average',
    scores: { hard_skills: 0, experience: 0, education: 0, soft_skills: 0, languages: 0, culture_fit: 0 },
    strengths: [], weaknesses: [], summary: '', recommendations: [],
    green_flags: [], red_flags: [], growth_potential: 'medium',
    form_responses: { 'Образование': 'ТГТУ, Программная инженерия, 2021', 'Опыт работы': '4 года в веб-разработке', 'Технические навыки': ['Python', 'Django', 'FastAPI', 'PostgreSQL', 'Docker'], 'Ожидаемая зарплата (USD в месяц)': '3000' },
  },
];
